import { NodeIO } from '@gltf-transform/core';
import { dedup, prune, weld } from '@gltf-transform/functions';
import sharp from 'sharp';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { prepareVehicleCollision } from './prepare-vehicle-collision.mjs';
// Source: Cesium GroundVehicle, Copyright 2018 Analytical Graphics, Inc.
// Apache-2.0. Adapted: original wheels removed, wheelbase/overhangs resized,
// normals regenerated by renderer, textures converted to mobile-sized WebP.
const revision = '113c068e9af33dba22e5cc54f5a762b593ca3829';
const origin = `https://raw.githubusercontent.com/CesiumGS/cesium/${revision}`;
await mkdir('.local', { recursive: true });
const source = '.local/ground-vehicle.glb';
for (const [path, local] of [['Apps/SampleData/models/GroundVehicle/GroundVehicle.glb', source], ['LICENSE.md', '.local/cesium-license.md']]) {
  const response = await fetch(`${origin}/${path}`); if (!response.ok) throw new Error(`Vehicle source: ${response.status}`);
  await writeFile(local, new Uint8Array(await response.arrayBuffer()));
}
const io = new NodeIO(), doc = await io.read(source);
for (const n of doc.getRoot().listNodes()) if (n.getName().startsWith('Wheels')) n.dispose();
const mesh = doc.getRoot().listNodes().find(n => n.getName() === 'GroundVehicle').getMesh();
for (const p of mesh.listPrimitives()) {
  const a = p.getAttribute('POSITION'), v = a.getArray();
  for(let i=0;i<v.length;i+=3){
    const originalX=v[i], originalY=v[i+1], z=v[i+2];
    let x=(z+.129296)*.50562;
    if(Math.abs(x)>1.28) x=Math.sign(x)*(1.28+(Math.abs(x)-1.28)*.45);
    v[i]=x;v[i+1]=(originalY-.580346)*.50562-.25;v[i+2]=-(originalX-.061882)*.62;
  }
  for(const attr of ['NORMAL','TANGENT']) p.setAttribute(attr,null);
}
for (const t of doc.getRoot().listTextures()) t.setImage(await sharp(t.getImage()).resize({ width:1024,height:1024,fit:'inside',withoutEnlargement:true }).webp({quality:88}).toBuffer()).setMimeType('image/webp');
await doc.transform(weld(),dedup(),prune());
doc.getRoot().getAsset().copyright='Copyright 2018 Analytical Graphics, Inc. Apache-2.0. Modified for FORMDRIVE: wheels removed; dimensions and textures adapted.';
await io.write('public/assets/offroad.glb',doc);
await prepareVehicleCollision();
const license = await readFile('.local/cesium-license.md','utf8');
await writeFile('public/licenses/cesium-vehicle.txt', 'GroundVehicle\nCopyright 2018 Analytical Graphics, Inc.\nSource: https://github.com/CesiumGS/cesium/tree/main/Apps/SampleData/models/GroundVehicle\nModified for FORMDRIVE: original wheels removed, proportions adapted, maps resized and compressed.\n\n'+license);
const input = await readFile(source), output = await readFile('public/assets/offroad.glb');
await writeFile('public/assets/offroad-source.json',JSON.stringify({title:'GroundVehicle',author:'Analytical Graphics, Inc.',year:2018,license:'Apache-2.0',source:'https://github.com/CesiumGS/cesium/tree/main/Apps/SampleData/models/GroundVehicle',revision,download:`${origin}/Apps/SampleData/models/GroundVehicle/GroundVehicle.glb`,originalSHA256:createHash('sha256').update(input).digest('hex'),adaptedSHA256:createHash('sha256').update(output).digest('hex'),changes:'Removed stock wheels; adapted dimensions for two drawn axles; resized and compressed PBR textures.'},null,2));
console.log({bytes:output.length});
